# Generated by Django 3.2.6 on 2024-01-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='topclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('product', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Top Clients',
            },
        ),
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('have_branch', models.BooleanField(default=True)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MesasgeToSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('checkbox', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negbuyapi.userdb')),
            ],
        ),
        migrations.CreateModel(
            name='clientreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('review_headline', models.CharField(max_length=255)),
                ('written_review', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('main_product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.productdb')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negbuyapi.userdb')),
            ],
            options={
                'verbose_name_plural': "Client's Review",
            },
        ),
    ]
