# Generated by Django 3.2.6 on 2024-01-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0003_auto_20240105_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesasgetosupplier',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
