# Generated by Django 3.2.6 on 2024-01-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0005_dealsproductsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsproductsinfo',
            name='ImageOfProduct',
            field=models.ImageField(blank=True, null=True, upload_to='dealofthedayproduct'),
        ),
    ]
