# Generated by Django 3.2.6 on 2024-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0006_alter_dealsproductsinfo_imageofproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='company_gst_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='identification_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='person_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse_personal_profile'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='store_manager_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='store_manager_id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse_id_proof'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='total_deliveries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
    ]
