# Generated by Django 3.2.6 on 2024-01-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0007_auto_20240109_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negbuy_warehouse',
            old_name='warehouse_image',
            new_name='warehouse_image1',
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image2',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image3',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image4',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image5',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image6',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
    ]
