# Generated by Django 3.2.6 on 2024-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0008_auto_20240109_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealsproductsinfo',
            name='ImageOfProduct',
        ),
    ]
