# Generated by Django 3.2.6 on 2024-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0009_remove_dealsproductsinfo_imageofproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image7',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image8',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
        migrations.AddField(
            model_name='negbuy_warehouse',
            name='warehouse_image9',
            field=models.ImageField(blank=True, null=True, upload_to='ware_house_img'),
        ),
    ]
